#!/usr/bin/env bash
set -euo pipefail

# This script is the main entry point to bootstrap a full configuration
# on a new computer.

# Bootstrap config with a fiew required packages.
REQ_PKG="cmake curl gcc gdb git jq lazygit make kitty stow wget xsel"
MISSING_PKG=()
for pkg in $REQ_PKG ; do
  if path=$(command -v "${pkg}" 2>/dev/null) ; then
    echo "${pkg} -> ${path}"
  else
    echo "${pkg} -> Missing"
    MISSING_PKG+=("${pkg}")
  fi
done

if [[ ${#MISSING_PKG[@]} -gt 0 ]] ; then
  echo "Installing missing package(s): ${MISSING_PKG[*]}"
  sudo apt install "${MISSING_PKG[@]}"
fi

# Install rust and rust tools
if path=$(command -v rustup 2> /dev/null) ; then
  rustup self update
  rustup update
else 
  # Install rust toolchain without modifying PATH as it is already in stowed config files
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -q -y -c rust-analyzer --no-modify-path
  source "$HOME/.cargo/env"
  cargo install ripgrep
  cargo install bacon
fi

# Install lua_language_server 
LUALS_VERSION="3.18.2"
install_lua_language_server "$LUALS_VERSION"

NEOVIM_VERSION="v0.12.2"
install_neovim "$NEOVIM_VERSION"

