#!/usr/bin/env bash
set -euo pipefail

# This script is the main entry point to bootstrap a new computer

# Install required packages
# TODO: Use apt or dpkg to check whether a Debian package is installed.
REQ_PKG="cmake curl gcc gdb git jq lazygit make kitty stow wget xsel"
MISSING_PKG=()
for pkg in $REQ_PKG ; do
  if path=$(command -v "${pkg}" 2>/dev/null) ; then
    echo "${pkg} -> ${path}"
  else
    echo "${pkg} -> Missing"
    MISSING_PKG+=("${pkg}")
  fi
done

if [[ ${#MISSING_PKG[@]} -gt 0 ]] ; then
  echo "info: Installing missing package(s): ${MISSING_PKG[*]}"
  sudo apt install "${MISSING_PKG[@]}"
fi

# Bootstrapping
DIR=$(dirname $0)
SETUP_ROOT_DIR=$(realpath $DIR)
SETUP_PKGS_DIR="$SETUP_ROOT_DIR/Pkgs"

echo "info: bootstrapping system..."
echo "info: SETUP_ROOT_DIR: $SETUP_ROOT_DIR"
echo "info: SETUP_PKGS_DIR: $SETUP_PKGS_DIR"

# Remove existing shell configuration files.
[ -e "$HOME/.bashrc" ] && rm "$HOME/.bashrc" 
[ -e "$HOME/.profile" ] && rm "$HOME/.profile"

# Write Setup env variables 
[ -d "$HOME/.profile.d" ] || mkdir -p "$HOME/.profile.d"
[ -e "$HOME/.profile.d/setup.env" ] && rm "$HOME/.profile.d/setup.env"
echo "export SETUP_ROOT_DIR=$SETUP_ROOT_DIR" >> "$HOME/.profile.d/setup.env"
echo "export SETUP_PKGS_DIR=$SETUP_PKGS_DIR" >> "$HOME/.profile.d/setup.env"

# Bootstrap shell configuration
stow -S -d "$SETUP_PKGS_DIR" -t "$HOME" shell
. "$HOME/.profile"

echo "info: system has been bootstrapped. To setup additional modules:"
echo "  '$ setup <module1>'"


