#!/usr/bin/env bash
set -euo pipefail

# This script is the main entry point to bootstrap a new computer

DIR=$(dirname $0)

# Install required packages
REQ_PKG="cmake curl gcc gdb git jq lazygit make kitty stow wget xsel"
MISSING_PKG=()
for pkg in $REQ_PKG ; do
  if path=$(command -v "${pkg}" 2>/dev/null) ; then
    echo "${pkg} -> ${path}"
  else
    echo "${pkg} -> Missing"
    MISSING_PKG+=("${pkg}")
  fi
done

if [[ ${#MISSING_PKG[@]} -gt 0 ]] ; then
  echo "Info : Installing missing package(s): ${MISSING_PKG[*]}"
  sudo apt install "${MISSING_PKG[@]}"
fi

# Install rust and rust tools
if path=$(command -v rustup 2> /dev/null) ; then
  rustup self update
  rustup update
  cargo install-update -a
else 
  # Install rust toolchain without modifying PATH as it is already in stowed config files
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -q -y -c rust-analyzer --no-modify-path
  source "$HOME/.cargo/env"
  cargo install cargo-update
  cargo install ripgrep
  cargo install bacon
fi

# Install lua_language_server 
LUALS_VERSION="3.18.2"
"$DIR"/bins/bin/install_lua_language_server "$LUALS_VERSION"

# Install neovim
NEOVIM_VERSION="v0.12.2"
"$DIR"/bins/bin/install_neovim "$NEOVIM_VERSION"

# Make sure we call stow from ~/Setup so that
# the stow directory is '~/Setup' and 
# the target direcotry is '~/'.
# See 'info stow' for the terminology and why it matters
if pushd ~/Setup >/dev/null ; then
  stow -S shell
  popd >/dev/null
else
  echo "Error: No '~/Setup' directory." >&2 ; exit 1
fi
